server:
  port: 13333

spring:
  application:
    name: dd-biz

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
